### ISSUE TITLE
Misc. fixes regarding stats

### ISSUE THREAD

**Issue by jimmydorry** [MNoya/PMP#1]
Please action the following
- remove the steamID hackery (we have that sorted)
- fix your roundIDs (more below)
- merge your library change upstream

You are submitting roundID+1 for phase3 and custom phase. Please start your rounds at 0 as a string. I can fix the DB for your mod when you have fixed that, but you will need to tell me what matchID you implemented at http://getdotastats.com/#s2__mod_rg?id=96

**Comment by MNoya** [comment]
Should be all fixed now, let me know if any issues still persist.

**Comment by jimmydorry** [comment]
Probably fixed
