### ISSUE TITLE
Theory on the Immortal creeps(speculation)

### ISSUE THREAD

**Issue by ghost** [MNoya/PMP#29]
Wasn't sure where to report this so here it is.  No doubt you're already aware of this and may even have a fix, if so then disregard what I have put here.

So it's been around for a few patches now and basically what happens is that occasionally when a creep dies it'll be at 0 health but not die and sit there in the camp spot for the rest of the game.  It doesn't have too much of an effect on gameplay except when the enemy lures the stronger ones  over to your side of the map but it's still annoying not being able to.

I've got this theory that the bug is caused by a player being able to indirectly damage multiple creeps (ie. not using a regular right-click) and have them die in the same instance.  From what I've seen it happens most commonly when a hero with cleave or an AOE farming ability tries to clear a camp and they always seem to spawn in pairs.  If this is the case then there is obviously another variable I've not been able to figure out (game time or number of bosses killed or something) because camps get cleared very quickly all the time.
I also noticed that this seems to (unconfirmed at this point) happen mostly in the early game and not much in the later game and I'd hazard a guess that this could potentially indicate that the bug is more likely to occur from heroes without upgraded boots of some kind. TBH I don't know enough about the inside workings of the game to really go in depth but there's the overall theory at least.

A couple of extra notes:
 - Farming cave TP boundaries need to be adjusted, I was standing behind the radiant boss closest to the dire side on the bottom inside the offside aura killing a boss and they cleared their cave and even though I was 2/3 of the length of the map away I got TP'd back to my base
 - Ogre boss needs to have increased cooldowns, he shouldn't be able to perma-stunned  someone imo... his ground pound has perma-stunned the entire squad trying to take him out
 - Ping Lag: for some reason, pinging the recipe to an upgrade will cause the entire game to lag for a second or two and sometimes even crash people. This has only happened on the upgrade recipe's for items so far

**Comment by DarthRecca** [comment]
Seems to be problem with OAA/PMP crossover.
Closing Issue
