### ISSUE TITLE
Make an AI replace empty player spots

### ISSUE THREAD

**Issue by Dragovorn** [MNoya/PMP#3]
Playing this game with my mates is relatively annoying due to there not being enough of us to fill an entire lobby, and it becomes the game of "Who spawns where", so I propose, either making bases that are not filled with players spawn an outpost that when defeated gives a modest amount of resources, or just replacing empty slots with computer controlled players that just attack the people next to it, and has a basic upgrade algorithm IE
- Weapon
- Armour
- Helm
- Health
- Repeat

Just an idea.

**Comment by MNoya** [comment]
Is spawn location actually relevant at the latest version? I feel it was solved/alleviated with the teleporters.

I wanted to do some AI bots for this regardless, it's not that hard, just no plans for it in the nearest future

**Comment by Dragovorn** [comment]
When your playing with 4 or 5 people yeah, it can get pretty bad, due to longer travel time even with the portals, especially when they spawn right next to eachother, they become way more farmed than you.
