### ISSUE TITLE
Item not allowed on hero for all combination items

### ISSUE THREAD

**Issue by hanseltime** [MNoya/PMP#30]
I can't really tell you what I did to create this bug.  But I was playing as medusa and went to purchase a level 2 satanic and was informed that the item could not be purchased on that hero.  I tried to purchase it again and there was no luck.  Then all items showed that flag if they were the result of a combination.  I dropped most of my stash and then bought an octarine core and things seemed to work for a second before i had the same problem again.  Sounds like there is a restriction that is propagating to other items when triggered.

**Comment by DarthRecca** [comment]
Closing issue as it seems unrelated to PMP
